{% set name = "text_extensions_for_pandas" %}
{% set version = "0.1b4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/CODAIT/text-extensions-for-pandas/archive/{{ version }}.tar.gz
  sha256: 46583b6147b54c61a6f86e4e40390de402740560c8bafb54074f07800bdc253f

build:
  number: 0
  skip: true  # [win or py<36]
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - python
  host:
    - python
    - pip
  run:
    - python
    - numpy >=1.17
    - pandas >=1.0.3
    - pyarrow >=1.0.0
    - regex
    - memoized-property
    - requests

test:
  imports:
    - text_extensions_for_pandas

about:
  home: https://github.com/CODAIT/text-extensions-for-pandas
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: "Natural language processing support for Pandas DataFrames."
  doc_url: https://text-extensions-for-pandas.readthedocs.io/en/latest/
  dev_url: https://github.com/CODAIT/text-extensions-for-pandas

extra:
  recipe-maintainers:
    - frreiss
    - BryanCutler
